# Generated by Django 4.2.2 on 2023-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='created_date',
            field=models.DateTimeField(auto_now=True, help_text='Date of adding file to document', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='document',
            name='label',
            field=models.CharField(help_text='Simple name of Document Folder at creation. NOT name of actual file', max_length=50, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='filename',
            field=models.CharField(help_text='Actual filename to be stored after renamed according to predecided scheme of file labelling', max_length=50, verbose_name='FileName'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='is_stub',
            field=models.BooleanField(default=True, help_text='when database entry exists but file operation is failed or file does not physically exist', verbose_name='Stub'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='revision_comment',
            field=models.TextField(blank=True, help_text='Information given by employee to manager after completion of given task and file upload', max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('i', 'Issued'), ('p', 'In Progress'), ('r', 'Revised'), ('a', 'Approved'), ('f', 'Final'), ('z', 'Archived')], help_text='File status set at every movement of file Causes file to show up at various dashboards', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='task_comment',
            field=models.TextField(blank=True, help_text='Instruction given by manager to employee at time of issuing file for modification', max_length=200, null=True, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='version',
            field=models.IntegerField(default=0, help_text='Major modification to file saved as reference point Always saved to central store', verbose_name='Version'),
        ),
    ]
