# Generated by Django 4.2.2 on 2023-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documentfile_created_date_alter_document_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of adding document to project', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of adding file to document', verbose_name='Created'),
        ),
    ]
