# Generated by Django 4.2.2 on 2023-06-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='full project name', max_length=200, verbose_name='Name')),
                ('short_code', models.CharField(help_text='short project code to use in file naming', max_length=4, verbose_name='Code')),
                ('start_date', models.DateField(auto_now=True, help_text='Start date of Project', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='End date of Project', null=True, verbose_name='End Date')),
                ('avtive_status', models.BooleanField(default=True, help_text='Project active status', verbose_name='Active')),
                ('description', models.TextField(blank=True, help_text='Short Project Description and or Information', max_length=500, null=True, verbose_name='Description')),
                ('project_folder', models.CharField(blank=True, help_text='Project Folder where all project files are centrally stored', max_length=200, null=True, verbose_name='Folder')),
                ('manager', models.ForeignKey(blank=True, help_text='Project Manager, who creates and manages team and activity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employee', verbose_name='Manager')),
                ('members', models.ManyToManyField(help_text='Employees added to project team, manager is default member', related_name='team', to='company.employee', verbose_name='Team')),
            ],
        ),
    ]
