# Generated by Django 4.2.2 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Full project name', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_code',
            field=models.CharField(help_text='Short project code to use in file naming', max_length=4, verbose_name='Code'),
        ),
    ]
