# Generated by Django 4.2.2 on 2023-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_name_alter_project_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, help_text='Start date of Project', null=True, verbose_name='Start Date'),
        ),
    ]
