# Generated by Django 4.2.2 on 2023-06-25 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full company Name, used in page title etc', max_length=100, verbose_name='Company Name')),
                ('short_code', models.CharField(help_text='Company short code to use in file naming', max_length=4, verbose_name='Short Code')),
                ('fileserver_ip', models.GenericIPAddressField(blank=True, help_text='Local IP address of central file server', null=True, verbose_name='Server IP')),
                ('fileserver_name', models.CharField(help_text='Computer name of fileserver', max_length=50, verbose_name='Server Name')),
                ('fileserver_user', models.CharField(help_text='Username of fileserver computer', max_length=50, verbose_name='Server User')),
                ('fileserver_folder', models.CharField(help_text='Folder on Fileserver where all file are stored', max_length=100, verbose_name='Server Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Designation', max_length=100, verbose_name='Title')),
                ('employee_crud_permission', models.BooleanField(default=False, help_text='Permission required to add, update and delete employee', verbose_name='Employee Permission')),
                ('project_crud_permission', models.BooleanField(default=False, help_text='Permission required to add , update and delete project', verbose_name='Project Permission')),
                ('document_crud_permission', models.BooleanField(default=False, help_text='Permission required to add , update and delete document', verbose_name='Document Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, help_text='employee join date', null=True, verbose_name='Join Date')),
                ('date_left', models.DateField(blank=True, help_text='employee left date', null=True, verbose_name='Left Date')),
                ('shared_folder', models.CharField(blank=True, help_text='Folder path string of employees local shared folder', max_length=200, null=True, verbose_name='Folder')),
                ('pc_name', models.CharField(blank=True, help_text='PC name of employee to access file share', max_length=50, null=True, verbose_name='PC Name')),
                ('local_ip', models.GenericIPAddressField(blank=True, help_text='IP address of employee PC to access file share', null=True, verbose_name='Local IP')),
                ('bio', models.TextField(blank=True, help_text='Short employee profile to store qualifications, experience etc', max_length=500, null=True, verbose_name='Bio')),
                ('designation', models.ForeignKey(help_text='Employee designation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.designation', verbose_name='Designation')),
                ('user', models.OneToOneField(help_text='User model Djnago Builtin', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
