# Generated by Django 4.2.2 on 2023-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fileserver_name',
            field=models.CharField(blank=True, help_text='Computer name of fileserver', max_length=50, null=True, verbose_name='Server Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fileserver_user',
            field=models.CharField(blank=True, help_text='Username of fileserver computer', max_length=50, null=True, verbose_name='Server User'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_code',
            field=models.CharField(help_text='Company short code to use in file naming', max_length=10, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='document_type_permission',
            field=models.ManyToManyField(blank=True, help_text='Document Types allowed to this designation', null=True, related_name='allowed', to='document.documenttype', verbose_name='Permitted Types'),
        ),
    ]
