# Generated by Django 4.2.2 on 2023-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('company', '0003_alter_company_fileserver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='document_type_permission',
            field=models.ManyToManyField(help_text='Document Types allowed to this designation', related_name='allowed', to='document.documenttype', verbose_name='Permitted Types'),
        ),
    ]
