# Generated by Django 4.2.2 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_designation_document_type_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(blank=True, help_text='Employee join date', null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_left',
            field=models.DateField(blank=True, help_text='Employee left date', null=True, verbose_name='Left Date'),
        ),
    ]
